Description: > 
  CICD with Circle CI

Parameters:
  AMItoUse:
    Description: AMI to use for our base image
    Type: AWS::EC2::Image::Id
    Default: ami-09d9c897fc36713bf

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: AWS-demo.pem
      InstanceType: t3.micro
      ImageId: !Ref AMItoUse
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
